#!/bin/bash

OSNAME=`cat /etc/issue | awk '{print $1}'`
OSNUM=`cat /etc/issue | awk '{print $2}'`
RADEONPRESENT=`lspci | grep VGA | grep -c Radeon`
ATIPRESENT=`lspci | grep VGA | grep -c 'ATI Technologies Inc'`
AMDSDKNAM="AMD-APP-SDK-v2.9-lnx64.tgz"
AMDSDKSUM="24ca89856d41aa82dea8370b7a24fb4e"
AMDDRVNAM="amd-catalyst-13.12-linux-x86.x86_64"
AMDDRVSUM="6b16cad1acf7aa4851fa00e43b9e3c1f"

# Display yellow warning output
function cwarn() {
        COLOR='\033[01;33m'     # bold green
        RESET='\033[00;00m'     # normal white
        MESSAGE=${@:-"${RESET}Error: No message passed"}
        echo -e "${COLOR}${MESSAGE}${RESET}"
}

# Display red error output
function cerr() {
        COLOR='\033[01;31m'     # bold red
        RESET='\033[00;00m'     # normal white
        MESSAGE=${@:-"${RESET}Error: No message passed"}
        echo -e "${COLOR}${MESSAGE}${RESET}"
}

# Display green warning output
function cinfo() {
        COLOR='\033[01;32m'     # bold green
        RESET='\033[00;00m'     # normal white
        MESSAGE=${@:-"${RESET}Error: No message passed"}
        echo -e "${COLOR}${MESSAGE}${RESET}"
}

function check_status() {
	local status=$1
	if [ $status -gt 0 ]
	then
		cerr "Something went wrong, please check you settings and try again."
		exit 1
	fi
}

if [ $RADEONPRESENT -lt 1 ]
then
	cerr "It appears you don't have an AMD Radeon present however we will install anyway as many vendor strings are inaccurate. Here is your card information:"
	cwarn `lspci | grep VGA`
else 
	cinfo "Found the following Radeon device(s):"
	cwarn `lspci | grep VGA | grep Radeon | awk 'match($0,"controller:"){print substr($0,RSTART+12)}'`
	cinfo "Continuing..."
fi

if [ "$OSNAME" == "Ubuntu" ]
then
	cinfo "Ubuntu version $OSNUM found, continuing..."
else
	cerr "This script is designed for Ubuntu, cancelling..."
	exit 1
fi

if [ `arch` == "x86_64" ];
then	
	cinfo "64 bit OS found, continuing..."
else
	cerr "32 bit OS not supported. Please install 64 bit OS to continue (Are you really still running a 32 bit processor?)"
	exit 1
fi

cinfo "Downloading AMD APP SDK..."
if [ -f $AMDSDKNAM ]
then
	cwarn "File $AMDSDKNAM exists, checking md5 hash..."
	if [ $AMDSDKSUM == `md5sum ./$AMDSDKNAM | awk '{print $1}'` ]
	then
		cinfo "File is OK! Skipping Download."
	else
		cerr "File is corrupt, redownloading..."
		rm -f ./$AMDSDKNAM
		check_status $?
		wget http://162.243.73.208/$AMDSDKNAM
		check_status $?
	fi
else
        wget http://162.243.73.208/$AMDSDKNAM
        check_status $?
fi

cinfo "Extracting AMD APP SDK..."

cd ~
check_status $?

cd mine-working
check_status $?

tar vxzf $AMDSDKNAM
check_status $?

cinfo "Installing AMD APP SDK (for openCL support)..."
sed "s/alarm(60);/alarm(1);/g" -i default-install_lnx_64.pl
sudo ./Install-AMD-APP.sh
check_status $?
rm -rf ~/mine-working
check_status $?
cinfo "It appears everything installed correctly!"
exit
